apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: priceline-server
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: priceline-server
      match:
        any:
          - resources:
              kinds:
                - Deployment
      verifyImages:
        - imageReferences:
            - "priceline-server:*"
          attestors:
            - entries:
                - keys:
                    publicKeys: |
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDM/PZvHJbzu7VjBLhL+HIB5XTFO2
                      q7RvKU9v7FqV1tz/iw0BDaK9mQR5DidM4BIjUsgUyyM4pSX2S3X71dXvtQ==
                      -----END PUBLIC KEY-----
